name: PronounMC
version: '${project.version}'
main: io.github.acekironcommunity.pronounmc.MyPlugin
api-version: 1.13
authors: [ AceKiron, Purrrpley, werken23 ]
description: See someone's pronouns
website: https://github.com/AceKiron-Community/pronounmc

softdepend: [ PlaceholderAPI ]

commands:
  addpronoun:
    description: "Add a pronoun to yourself or somebody else"
    usage: /addpronoun <pronoun> [player]
    aliases: addpronouns
    permission: pronounmc.modify
    permission-message: "PronounMC: Missing the pronounmc.modify permission."
  removepronoun:
    description: "Remove a pronoun from yourself or somebody else"
    usage: /removepronoun <pronoun> [player]
    aliases: removepronouns
    permission: pronounmc.modify
    permission-message: "PronounMC: Missing the pronounmc.modify permission."
  getpronouns:
    description: "Get the list of pronouns of yourself or somebody else"
    usage: /getpronouns [player]
    permission: pronounmc.get
    permission-message: "PronounMC: Missing the pronounmc.get permission."
  pmcreload:
    description: "Reload everything related to PronounMC"
    usage: /pmcreload
    permission: pronounmc.reload
    permission-message: "PronounMC: Missing the pronounmc.reload permission."